### ISSUE TITLE
DecodeVideo: kNoKey for key ... on HD streams

### ISSUE THREAD

**Issue by mooninite** [xbmc/inputstream.adaptive#212] opened 2018-12-12 05:06 UTC
Fedora 29 x86_64
Kodi 18 RC2
inputstream.adaptive 2.3.12
widevine 1.4.9.1088

I am attempting to play a purchased movie in the YouTube add-on. The movie will start playing but 10 seconds in the video stream feezes and the following error is printing in the log:

ERROR: AddOnLog: InputStream Adaptive: DecodeVideo: kNoKey for key (KEY REDACTED)

Audio continues to play with a frozen video stream. Are YouTube purchases supposed to play?

I can play 480p video streams, but 720p or 1080p freeze after 10 seconds.

**Comment by mooninite** [comment] 2018-12-13 03:05
I installed the Netflix plugin today and I can play 480p, 720p, and 1080p streams without any issues.

**Comment by Clubfan22** [comment] 2018-12-14 21:37
Thank you so much for your work on inputstream-adaptive

I can confirm a similar (probably the same) issue for Amazon Prime Video.
When I try to play a movie, no video is being played (although sound works fine) and the same error as OP has is being logged. When I try to play an episode of a TV series, everything works fine (regardless of resolution).

I'm running
Arch Linux
Kodi  18.0-RC3 Git: 20181214-4c17e7769e5 (built with -O3 and -march=native, installed through [AUR](https://aur.archlinux.org/packages/kodi-git/))
[Amazon VOD](https://github.com/Sandmann79/xbmc/tree/master/plugin.video.amazon-test) Version 0.6.3
inputstream.adaptive 2.3.12 (installed through [AUR)](https://aur.archlinux.org/packages/kodi-addon-inputstream-adaptive-18-git/)
libvidewinecdm.so from the latest Chromium download

I'm more than happy to provide additional information if you'd like me too.

**Comment by Clubfan22** [comment] 2018-12-15 19:30
Further research shows that video playback works correctly when I change the following settings of InputStream-Adaptive:

Max. Resolution general decoder: 1080p -> 480p
Max. Resolution secure decoder: 1080p -> 480p

**Comment by Kleinrotti** [comment] 2018-12-21 16:05
I have the same kNoKey for key error on Windows 10 with Kodi 18.0-RC3. Movies from the netflix-addon only play in 480p but series in 1080p. In the Amazon-addon both only play 480p. If i choose 1080p  manually i only have audio.

**Comment by Varstahl** [comment] 2019-01-10 22:55
@Kleinrotti not sure of what addon you're talking about, but if it's the Amazon/Amazon VOD (https://github.com/Sandmann79/xbmc) then they play 1080p series.

It's just movies that won't go [past 480p](https://github.com/Sandmann79/xbmc/issues/51#issuecomment-450206910).

**Comment by Varstahl** [comment] 2019-01-14 21:38
I wanted to update you guys on the issue, since this is broader than just Netflix (which works, atm).

I've been investigating the matter over at https://github.com/Sandmann79/xbmc/issues/51, and so far the most likely scenario is that HD streams require [VMP](https://storage.googleapis.com/wvdocs/Widevine_DRM_Proxy_Integration.pdf). Currently only browsers (through EME?) are able to acquire a `PLATFORM_SOFTWARE_VERIFIED`, while Kodi gets a `PLATFORM_UNVERIFIED`.

I'm doing a few tests through Firefox sources and the Widevine CDM binary it uses. If we are able to pass the software verification we will be able to watch every stream that doesn't require proprietary hardware (such as in android/chromecasts). Since everything is closed source (and at least partially protected from reverse engineering) it isn't the easiest reversing I've ever done, so if anybody here has experience with WV, VMP or EME, let me know.

**Comment by Varstahl** [comment] 2019-01-16 17:46
Last update: at least on Amazon's side, anything higher than 1088x464 won't run due to the strict enforcement of HDCP_V1 for movies. There is currently no known way around this. If you're experiencing a `kNoKey for key` on PCs, you can check the Widevine license API endpoint of the service you're using, and it's probably due to HDCP.

**Comment by FloridaStream** [comment] 2019-01-29 15:49
inputstream is ready for cdm 4.10.**1224**.7?

**Comment by peak3d** [comment] 2019-01-29 16:00
@FloridaStream I tested the newest libWidewine some weeks ago using windows, but had issues (segfaults) for reasons I don't know yet. Not sure if this was the version you mentioned, sry

**Comment by FloridaStream** [comment] 2019-03-23 05:12
hi @peak3d and @liberty-developer, see if you could tell if the inputstream.adaptive would still work after updating the wv VMP where checking the `platform_verification_status` is required as authentic? 
Reference: https://www.widevine.com/news

@Varstahl do you have any news?

**Comment by Varstahl** [comment] 2019-03-23 09:17
I don't have a box with either L1 encryption or HDCP ready, so no. If everyone applies their defaults, no other third party software will ever work, period. Remains to be seen.

**Comment by matthuo333** [comment] 2021-01-16 11:44
The HBO Max add-on has just happened to be VMP.

**Comment by glennguy** [comment] 2021-06-09 04:30
@mooninite This might have been fixed in #589... can we close this issue?

**Comment by mooninite** [comment] 2021-06-09 14:34
The problem still occurs. Same symptoms and same error message.

Kodi 19.1
InputStream Adaptive 2.6.16

**Comment by glennguy** [comment] 2021-06-10 02:35
@mooninite could you post a full debug log? It could be a VMP issue

**Comment by glennguy** [comment] 2021-06-10 03:47
Also useful to have would be the mpd as well

**Closed** 2021-09-28 12:14 UTC

**Comment by Mariusz89B** [comment] 2021-10-31 10:09
@glennguy Error persists while starting HD streams.
https://paste.ubuntu.com/p/42GCMs2QDy/

EDIT:
Tested on Kodi Nexus, I.A 20.0.2 with the same result.

**Comment by glennguy** [comment] 2021-11-01 00:00
Please use paste.kodi.tv for log uploads - that ubuntu site needs a verified account to view them...

I was able to retrieve the mpd from the log, there are also low resolution streams in there - are they able to be viewed?
I would suspect that what is happening is the license request goes out (with keyids from all video representations) and we get a successful response because at least one stream is playable/keyid returned. Probably due to VMP though the license server will not give us a key for the HD streams.
I'm assuming you can view the 1080p streams in a browser and would suspect that viewing them in an unsigned browser (e.g unofficial/self build) you would run into the same problem.

**Comment by Mariusz89B** [comment] 2021-11-01 04:59
@glennguy Yes, that is correct the low res strms are working and unsigned browsers are throwing the same error. 

Is there a solution to this issue to get a successful response from all streams?

**Comment by glennguy** [comment] 2021-11-01 05:52
The only way to get the keys I believe would be if Kodi was widevine certified. Never say never but I doubt that will happen.
Have a read here: https://blog.samuelmaddock.com/posts/the-end-of-indie-web-browsers/ , the Conclusion section doesn't give much hope.

We only know that there's no key once we try to decrypt, maybe there's a more graceful way to handle this and at least give the user something to watch. The solution would probably be Kodi 20+ though.

I would suggest for the add-on to proxy the mpd and remove the `AdaptationSet`s and `Representation`s that don't work.

**Comment by glennguy** [comment] 2021-11-01 09:54
Just FYI it would probably work fine in Kodi running on Android as long as it's an L1 certified device.

**Comment by Mariusz89B** [comment] 2021-11-01 10:08
@glennguy Good to know. Thank you for your information.
