### ISSUE TITLE
WARNING: ActiveAE - large audio sync error on Netflix Plugin

### ISSUE THREAD

**Issue by Vitocorl** [xbmc/inputstream.adaptive#249] opened 2019-04-03 09:46 UTC
I opened this at CastagnaIT/plugin.video.netflix, but since then i found that peak3d has already dealt with similar errors in Kodi and inputstream, so i closed the issue at CastagnaIT/plugin.video.netflix and i am continuing here:
The issue is that audio gets out of sync and video starts stuttering on Xiaomi Mibox S, Android TV 8.1
Addon version used plugin.video.netflix_0.14.0beta23_20190331.
I also installed the latest Kodi nightly(kodi-20190402-f8100282-master-armeabi-v7a), as i realized that peak3d has provided a fix for a similar error happening after skipping forward a video file in Kodi, but it does not fix it for me.

The problem occurs at the same videos and at the same time of the video each time, for example, at Luce Cage TV Show, episode "Manifest" after 30 seconds of play. If i scroll backwards or forward the video then it resumes playing normally. I suspect it is some kind of buffering problem, but it only occurs on the Kodi Netflix plugin and not in the Android app. I am not sure if it is a Netflix plugin error or an inputstream adaptive error.
I cleaned cache of Netflix plugin, but afterwards the same happens.
I also used an optimised advancedsettings.xml, but i do not think Netflix plugin is using it.

My Kodi debug log is too big (2,2Mb) and hastebin does not accept it, so i am attching it as a zip here...
[kodi_debug_log.zip](https://github.com/peak3d/inputstream.adaptive/files/3037989/kodi_debug_log.zip)

**Comment by Vitocorl** [comment] 2019-04-05 06:39
@peak3d 
Is there a way to adjust the buffer memory size in inputstream? i think my advancesettings.xml has no effect whatsoever. Moreover, i still cannot tell if this problem is due to Kodi or inputstream, the issues have started since about ten days ago...

**Comment by Vitocorl** [comment] 2019-04-11 07:12
@peak3d
Any idea about this problem, it keeps happening, i have updated Kodi to the latest nightly with no effect...

**Comment by Vitocorl** [comment] 2019-04-13 16:48
@peak3d
I have just checked and when the problem happens i can see the buffer going down to 0%, as long as the buffer is over 0% (even if it is at 5%) the video plays smoothly, it is a buffering problem, but i do not know how to adjust it in inputstream....

**Comment by peak3d** [comment] 2019-05-20 15:41
From log there is a A/V diff of ~ 8ms, what is not nice but should not be visible much.
First I would try to switch screen to 59.94Hz and enable "Sync Playback To Display"

Before you send another log, pls. try to reduce log spam (maybe ask addon maintainer tio clean up things) or disable JSON rpc component debugging.

**Comment by AlleSchonWeg** [comment] 2019-05-20 16:00
@peak3d Könnte dies auch das Problem mit dem DAZN Buffern sein, welches einige Leute (auch ich) haben? Es haben sich ja einige Leute im Kodinerds Forum darüber berichtet. Hab in einem alten Log auch die Warnung:
`2019-03-08 14:42:14.644 T:1916896112 WARNING: ActiveAE - large audio sync error: -89455.525146`

**Comment by peak3d** [comment] 2019-05-20 16:08
DAZN is different from what I remember from last investigation, they have PTS jump ssues between segments. But - this is just a guess, I cannot reproduce because I don't have Dazn.

**Comment by Vitocorl** [comment] 2019-05-21 04:44
> 
> 
> From log there is a A/V diff of ~ 8ms, what is not nice but should not be visible much.
> First I would try to switch screen to 59.94Hz and enable "Sync Playback To Display"
> 
> Before you send another log, pls. try to reduce log spam (maybe ask addon maintainer tio clean up things) or disable JSON rpc component debugging.

I will try to reduce the log, however, since the problem happens during playback, the log gets huge, i will disable JSON rpc component debugging and emby and hope for the best...

**Comment by rafhtl** [comment] 2021-04-04 22:04
I have the same problem on kodi 19
ActiveAE - large audio sync error
the log gets filled with this and at a certain point streaming stops and hangs kodi
thank you

**Comment by ratcashdev** [comment] 2021-05-24 18:54
Same issue, Kodi 19.1, only on specific streams and never on others (or it gracefully recovers).

**Comment by rafhtl** [comment] 2021-12-03 17:08
Hi I still have the issue in version 19
large audio sync error
filling my kodi.log
Help!
could you at least disable the warning log?
WARNING <general>: ActiveAE - large audio sync error: -1004.835002
thank you

**Comment by CrAcK75** [comment] 2022-01-17 22:28
I've the same issue playing:  https://supertennix-l3-live1.secure.footprint.net/restreamer/supertennix_client/gpu-b-c1-17/restreamer/rtmp/hls/h24_live/manifest.m3u8
I've a lot of 
WARNING <general>: ActiveAE - large audio sync error: 
and also 
ERROR <general>: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
and 
 WARNING <general>: CVideoPlayerVideo::OutputPicture - timeout waiting for buffer
as described here: https://github.com/xbmc/xbmc/issues/20089

Kodi only plays a few seconds and then stops the playback by freezing the image, in my case if I rewind a little AI it plays the video well but only for a few seconds, if I repeat the rewind it plays another couple of seconds and so on ... could i fix it or is a fix needed?

This happen on Matrix 19.3, IA 19.0.2

**Comment by glennguy** [comment] 2022-01-18 05:50
@CrAcK75 the same warning in the log != same issue.

Luckily I can access that stream from where I am, and whether it's played in Kodi, VLC, or Chrome there's an issue with the audio sync. It seems to be several seconds out. This could be causing the other symptoms seen or maybe completely unrelated. I can see from my log that inputstream.adaptive seems to skip over a segment after ~10 or so seconds so maybe there is something that can be done.

**Comment by CrAcK75** [comment] 2022-01-18 16:20
> Luckily I can access that stream from where I am, and whether it's played in Kodi, VLC, or Chrome there's an issue with the audio sync. 

Thank you for your answer @glennguy, unfortunately, to date that streaming is not available, I think the site has some problems, but in the last few days if I was playing the streaming online there were no visual problems, only kodi freezed the image.

For now I've to wait

**Comment by glennguy** [comment] 2022-01-18 21:21
@CrAcK75 fix is in progress, please see #878 
Once backported to Matrix I will do a release

**Comment by CrAcK75** [comment] 2022-01-19 16:24
> Once backported to Matrix I will do a release

Thank you

**Comment by glennguy** [comment] 2022-01-30 03:53
@CrAcK75 could you please test the changes, zips for win/mac/android can be had from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-891/1/artifacts

**Comment by CrAcK75** [comment] 2022-01-31 09:37
> @CrAcK75 could you please test the changes, zips for win/mac/android can be had from here: https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.adaptive/detail/PR-891/1/artifacts

Hi, first test it's seems to be OK, but I'll test better and I'll say you
Thank you so mutch for now

**Comment by CastagnaIT** [comment] 2022-03-01 08:23
the changes has been merged and released in the last version,
it would be good to get feedback also from Issue author @Vitocorl
if no feedback in next days this Issue will be closed

**Closed** 2022-03-08 08:32 UTC
Labels: Issue Cleanup: Closed

**Comment by CrAcK75** [comment] 2022-03-10 10:07
> the changes has been merged and released in the last version, it would be good to get feedback also from Issue author @Vitocorl if no feedback in next days this Issue will be closed

sorry for late but I had with high fever for a few days

on android seems to be ok but on Windows I continue to have very often a lot of WARNING <general>: ActiveAE - large audio sync error
there is another issue to follow?

**Comment by CastagnaIT** [comment] 2022-03-10 10:45
what kodi version on Windows? can you try on Kodi 20?
is a bit weird that happens ~only to you~ so rarely, from my tests i have also noticed that mentioned warning
could happens when the system is too busy thing that however can not be solved

for example with my low end pc happens when i watch videos while the system install windows updates or do something else operations that slow down the system, so until it finishes the system updates operations i have to pause the video

**Comment by CrAcK75** [comment] 2022-03-16 18:21
> what kodi version on Windows? can you try on Kodi 20? is a bit weird that happens ~only to you~ so rarely, from my tests i have also noticed that mentioned warning could happens when the system is too busy thing that however can not be solved
> 
> for example with my low end pc happens when i watch videos while the system install windows updates or do something else operations that slow down the system, so until it finishes the system updates operations i have to pause the video

No, I cannot try with Kodi 20, is not stable and I'm not interest until it become official, the issue is on Kodi 19 Matrix since 19.3 and it's not only my issue because we have an addon "WLTV" that groups a lot of free tvchannels and, many users has the same issue "ActiveAE - large audio sync error". Many of them (not all) has solve on a lot of channels with android (because on android now there is the 19.0.3 of InputStream) but the others has still issues. It's difficult to reproduce the issue because not many channels has a simple fixed url to the stream and also it's not a static issue I think it depends by stream.

**Comment by CastagnaIT** [comment] 2022-03-16 19:33
however i have tested your link of test stream on:
android honor with Kodi 20
windows with Kodi 19 and Kodi 20
and in all cases the stream is played correctly

ensure you have in kodi video settings:
hardware acceleration mediacodec surface -> ON
hardware acceleration mediacodec -> ON
sync playback to display -> OFF

this warning "ActiveAE - large audio sync error" not explains nothing
on kodi repository there are a lot of Issues opened (of different nature) that report that warnings

your problem appear a bit different, the author of this Issue thread say:

> The issue is that audio gets out of sync and video starts stuttering

instead you have reported this:

> Kodi only plays a few seconds and then stops the playback by freezing the image

the only way to try investigate is to have a test stream where we can reproduce the same issue from other devices
but it is better that you open a your Issue thread, by providing also the test stream

**Comment by CastagnaIT** [comment] 2022-03-16 19:43
also be reluctant not to do a test on Kodi 20 not help us to investigate,
the core of Kodi 20 and InputStreamAdaptive for Kodi 20 has different changes/fixes/improvements
therefore it will not be possible to tell whether the problem has already been solved
