### ISSUE TITLE
It's possible to add a manual size for cache ??

### ISSUE THREAD

**Issue by DjDiabolik** [xbmc/inputstream.adaptive#14] opened 2017-02-28 03:03 UTC
The inputstream.adaptive on kodi-17.x it's been used for example for youtube video.
The currently video addons 5.3.10 whitout inpustream activated have a your personal size for cache setted by default at 20MB....... 

Apparently this value it's not been used when kodi use, now, the inputstream.adaptive....... it's possible to add somethigs similar ?? I thinks this it's be usefull for example for live stream to create a little buffer before to start the reproduction and this helped expecilly who does not have a super fast connection...

**Comment by CaptainTK** [comment] 2017-03-01 20:43
I second to that. Ideally, please use the values specified in [advancedsettings.xml](http://kodi.wiki/view/HOW-TO%3AModify_the_video_cache).

**Comment by DjDiabolik** [comment] 2017-03-02 18:27
yeah.... i have that but apparently it's useless also to set this value to 500MB :) I thinks the only problems it's kodi 17.x.....

**Comment by peak3d** [comment] 2017-03-12 22:40
inputstream.adaptive does not use those internal kodi settings.
Currently 8 sec. internal kodi buffer is used. This is fixed and cannot be changed from outside.

Buffering is one of the next things which will be done.

**Comment by peterpan192** [comment] 2018-04-10 15:28
Is there an approximate time when it will be implemented?

**Comment by mirkorobocop** [comment] 2019-01-15 18:02
@peak3d Is this already implemented?

**Comment by glennguy** [comment] 2021-06-09 03:57
Duplicate of #8

**Closed by glennguy** 2021-06-09 03:57 UTC
